name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        pip install pytest pytest-cov
        pip install -r requirements.txt
        
    - name: Run tests with coverage
      run: |
        pytest --cov=test_mainbot.py test_mainbot.py